Repository UAlbanyArchives/mailbagit, pull requests merged in 2021-11, with the labels that each got.

#69 Documentation readme 45
  README.md
Labels: documentation

#67 PYTEST for PST
  data/outlook2019_MSO_16.0.10377.20023_64-bit.pst
  tests/test_Controller.py
  tests/test_formats.py
Labels: Tests

#72 Initial commit of derivative registry/abc
  mailbag/__init__.py
  mailbag/derivative.py
  mailbag/derivatives/example.py
  mailbag/email_account.py
Labels: Core

#74 Libpff require conditional 73
  mailbag/formats/pst.py
Labels: bug

#66 Creates directory structure for input files
  mailbag/__init__.py
  mailbag/controller.py
  mailbag/formats/mbox.py
  mailbag/formats/msg.py
  mailbag/formats/pst.py
  mailbag/helper.py
  tests/test_Controller.py
  tests/test_formats.py
Labels: Core
