Repository UAlbanyArchives/mailbagit, pull requests merged in 2022-05, with the labels that each got.

#148 Feedback mechanism 16
  Pipfile.lock
  mailbag/__init__.py
  mailbag/controller.py
  mailbag/formats/eml.py
  mailbag/formats/mbox.py
  mailbag/formats/msg.py
  mailbag/formats/pst.py
  mailbag/globals.py
  mailbag/helper.py
  mailbag/loggerx.py
  mailbag/models.py
  pyproject.toml
  tests/test_formats.py
Labels: Core

#159 allows google-chrome as a command for non-windows systems
  mailbag/derivatives/pdf-chrome.py
Labels: Derivatives

#164 now handles all file extensions regardless of case
  mailbag/formats/eml.py
  mailbag/formats/mbox.py
  mailbag/formats/msg.py
  mailbag/formats/pst.py
Labels: bug, Input

#158 fixed output
  mailbag/__init__.py
  mailbag/globals.py
  mailbag/helper.py
Labels: bug

#166 encoding hotfixes
  mailbag/controller.py
  mailbag/derivatives/eml.py
  mailbag/derivatives/html.py
  mailbag/derivatives/mbox.py
  mailbag/derivatives/pdf-chrome.py
  mailbag/derivatives/pdf.py
  mailbag/derivatives/txt.py
  mailbag/derivatives/warc.py
  mailbag/formats/eml.py
  mailbag/formats/mbox.py
  mailbag/formats/msg.py
  mailbag/formats/pst.py
  mailbag/helper.py
Labels: bug, Input

#175 Pst folders 117
  data/pst-outlook2019_MSO_16.0.10377.20023_64-bit/1/Derivatives_Path.txt
  data/pst-outlook2019_MSO_16.0.10377.20023_64-bit/1/Message_Path.txt
  data/pst-outlook2019_MSO_16.0.10377.20023_64-bit/2/Derivatives_Path.txt
  data/pst-outlook2019_MSO_16.0.10377.20023_64-bit/2/Message_Path.txt
  mailbagit/formats/pst.py
Labels: Input

#180 added manual utf-8 decode check for plain text pst bodies
  mailbagit/formats/pst.py
Labels: bug, Input

#181 external css now writes to <head><style> instead of a link
  mailbagit/helper/derivative.py
Labels: Derivatives

#182 Fixes #160 by manually importing derivatives and formats
  mailbagit/__init__.py
  mailbagit/derivative.py
  mailbagit/derivatives/eml.py
  mailbagit/derivatives/pdf_chrome.py
  mailbagit/email_account.py
Labels: Distribution

#185 added docs about executables back in
  docs/Gemfile.lock
  docs/install.md
  docs/installing_mailbagit/docker.md
  docs/installing_mailbagit/exe.md
  docs/installing_mailbagit/pdf.md
  docs/installing_mailbagit/python.md
  docs/using_mailbagit/mailbagit-gui.md
Labels: documentation

#187 Attachments.csv and inline attachment fixes
  data/msg-Digitization Archiving Solutions/1/Attachments/1/Content_ID.txt
  data/msg-Digitization Archiving Solutions/1/Attachments/2/Content_ID.txt
  data/msg-Digitization Archiving Solutions/1/Attachments/3/Content_ID.txt
  mailbagit/controller.py
  mailbagit/derivatives/eml.py
  mailbagit/derivatives/mbox.py
  mailbagit/derivatives/pdf.py
  mailbagit/formats/msg.py
  mailbagit/formats/pst.py
  mailbagit/helper/controller.py
  mailbagit/helper/derivative.py
  mailbagit/helper/format.py
  mailbagit/models.py
  tests/test_formats.py
Labels: bug, Attachments, Derivatives

#190 Mbox fixes
  Dockerfile.production
  docs/img/allow_executable.png
  docs/img/release_assets.png
  docs/installing_mailbagit/exe.md
  mailbagit/__init__.py
  mailbagit/derivatives/mbox.py
  release.md
  setup.py
Labels: bug

#196 fixed incompliant Content_Type header
  mailbagit/controller.py
  release.md
Labels: bug

#199 Version 193
  docs/using_mailbagit/mailbagit.md
  mailbagit/__init__.py
Labels: enhancement
