Repository UAlbanyArchives/mailbagit, pull requests merged in 2022-06, with the labels that each got.

#198 Split error reports
  mailbagit/controller.py
  mailbagit/derivatives/eml.py
  mailbagit/derivatives/html.py
  mailbagit/derivatives/mbox.py
  mailbagit/derivatives/pdf.py
  mailbagit/derivatives/pdf_chrome.py
  mailbagit/derivatives/txt.py
  mailbagit/derivatives/warc.py
  mailbagit/formats/eml.py
  mailbagit/formats/mbox.py
  mailbagit/formats/msg.py
  mailbagit/formats/pst.py
  mailbagit/helper/common.py
  mailbagit/helper/controller.py
  mailbagit/helper/format.py
  mailbagit/models.py
Labels: Core

#208 use new extractMsg attributes
  mailbagit/formats/msg.py
  setup.py
Labels: Attachments, Input

#205 Guided CLI input path
  mailbagit-guided.py
  mailbagit/__init__.py
  mailbagit/guided.py
  setup.py
Labels: Core

#212 error and warning documentaion
  docs/using_mailbagit/concerns.md
  docs/using_mailbagit/errors.md
  docs/using_mailbagit/logging.md
  docs/using_mailbagit/lossiness.md
  docs/using_mailbagit/plugins.md
Labels: documentation

#214 PDF derivative conflict
  mailbagit/__init__.py
Labels: bug
